import 'package:flutter/material.dart';
import 'package:fydez_elements/fydez_elements.dart';

class TestingPageMaker extends StatelessWidget {
  const TestingPageMaker({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return NormalFyPage(
      appBar: AppBar(
        title: const Text('Testing Page Maker'),
      ),
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.all(20.0),
      itemPadding: const EdgeInsets.symmetric(vertical: 10.0),
      elements: [
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
        SampleElement(),
      ],
    ).build(context);
  }
}
